package cleaner

import (
	"os"
	"path/filepath"
	"testing"
)

func TestBackupAndRestoreRoundTrip(t *testing.T) {
	tmpDir := t.TempDir()
	setupTestFiles(t, tmpDir, map[string]string{
		"CLAUDE.md":     "instructions",
		"CHANGELOG.md":  "# Changes",
		"main.go":       "package main\n\n// Generated by Claude\nfunc main() {}\n",
		"README.md":     "# Project",
		".claude/x.md":  "tool state",
		"docs/guide.md": "# Guide",
	})

	c := New(tmpDir, Options{Backup: true})
	for _, step := range c.Steps() {
		if step.Key == "history" {
			continue // needs a real git repo; covered elsewhere
		}
		if err := step.Run(); err != nil {
			t.Fatalf("step %s failed: %v", step.Key, err)
		}
	}
	dir, err := c.FinalizeBackup()
	if err != nil {
		t.Fatalf("FinalizeBackup() error = %v", err)
	}
	if dir == "" {
		t.Fatal("expected a backup directory to be created")
	}

	// Sanity: the cleaner actually removed and modified things.
	if _, err := os.Stat(filepath.Join(tmpDir, "CLAUDE.md")); !os.IsNotExist(err) {
		t.Fatal("expected CLAUDE.md to be removed")
	}
	if _, err := os.Stat(filepath.Join(tmpDir, "CHANGELOG.md")); !os.IsNotExist(err) {
		t.Fatal("expected CHANGELOG.md to be removed")
	}
	got, _ := os.ReadFile(filepath.Join(tmpDir, "main.go"))
	if string(got) == "package main\n\n// Generated by Claude\nfunc main() {}\n" {
		t.Fatal("expected main.go comment to be stripped")
	}

	if err := Restore(tmpDir, RestoreOptions{}); err != nil {
		t.Fatalf("Restore() error = %v", err)
	}

	want := map[string]string{
		"CLAUDE.md":    "instructions",
		"CHANGELOG.md": "# Changes",
		"main.go":      "package main\n\n// Generated by Claude\nfunc main() {}\n",
		".claude/x.md": "tool state",
	}
	for path, content := range want {
		got, err := os.ReadFile(filepath.Join(tmpDir, path))
		if err != nil {
			t.Errorf("%s not restored: %v", path, err)
			continue
		}
		if string(got) != content {
			t.Errorf("%s content mismatch:\ngot:  %q\nwant: %q", path, string(got), content)
		}
	}
}

func TestBackupDisabled(t *testing.T) {
	tmpDir := t.TempDir()
	setupTestFiles(t, tmpDir, map[string]string{"CLAUDE.md": "instructions"})

	c := New(tmpDir, Options{Backup: false})
	if err := c.CleanAIArtifacts(); err != nil {
		t.Fatalf("CleanAIArtifacts() error = %v", err)
	}
	dir, err := c.FinalizeBackup()
	if err != nil {
		t.Fatalf("FinalizeBackup() error = %v", err)
	}
	if dir != "" {
		t.Errorf("expected no backup dir, got %q", dir)
	}
	if _, err := os.Stat(filepath.Join(tmpDir, backupDirName)); !os.IsNotExist(err) {
		t.Error("backup directory should not exist when Backup is false")
	}
}

func TestBackupSkippedInDryRun(t *testing.T) {
	tmpDir := t.TempDir()
	setupTestFiles(t, tmpDir, map[string]string{"CLAUDE.md": "instructions"})

	c := New(tmpDir, Options{Backup: true, DryRun: true})
	if err := c.CleanAIArtifacts(); err != nil {
		t.Fatalf("CleanAIArtifacts() error = %v", err)
	}
	dir, err := c.FinalizeBackup()
	if err != nil {
		t.Fatalf("FinalizeBackup() error = %v", err)
	}
	if dir != "" {
		t.Errorf("dry run should not create a backup, got %q", dir)
	}
}

func TestBackupCreatesNothingWhenNoChanges(t *testing.T) {
	tmpDir := t.TempDir()
	setupTestFiles(t, tmpDir, map[string]string{"README.md": "# Project"})

	c := New(tmpDir, Options{Backup: true})
	if err := c.CleanAIArtifacts(); err != nil {
		t.Fatalf("CleanAIArtifacts() error = %v", err)
	}
	dir, err := c.FinalizeBackup()
	if err != nil {
		t.Fatalf("FinalizeBackup() error = %v", err)
	}
	if dir != "" {
		t.Errorf("expected no backup dir when nothing changed, got %q", dir)
	}
}

func TestBackupPreservesFileMode(t *testing.T) {
	tmpDir := t.TempDir()
	script := filepath.Join(tmpDir, "run.go")
	if err := os.WriteFile(script, []byte("package main // built by Claude\n"), 0o755); err != nil {
		t.Fatal(err)
	}

	c := New(tmpDir, Options{Backup: true})
	if err := c.CleanSourceComments(); err != nil {
		t.Fatalf("CleanSourceComments() error = %v", err)
	}
	if _, err := c.FinalizeBackup(); err != nil {
		t.Fatal(err)
	}
	if err := Restore(tmpDir, RestoreOptions{}); err != nil {
		t.Fatalf("Restore() error = %v", err)
	}

	info, err := os.Stat(script)
	if err != nil {
		t.Fatal(err)
	}
	if perm := info.Mode().Perm(); perm != 0o755 {
		t.Errorf("restored mode = %o, want 755", perm)
	}
}

func TestRestoreDryRunWritesNothing(t *testing.T) {
	tmpDir := t.TempDir()
	setupTestFiles(t, tmpDir, map[string]string{"CLAUDE.md": "instructions"})

	c := New(tmpDir, Options{Backup: true})
	if err := c.CleanAIArtifacts(); err != nil {
		t.Fatal(err)
	}
	if _, err := c.FinalizeBackup(); err != nil {
		t.Fatal(err)
	}

	if err := Restore(tmpDir, RestoreOptions{DryRun: true}); err != nil {
		t.Fatalf("Restore() error = %v", err)
	}
	if _, err := os.Stat(filepath.Join(tmpDir, "CLAUDE.md")); !os.IsNotExist(err) {
		t.Error("dry-run restore should not recreate files")
	}
}

func TestRestoreWithoutBackupErrors(t *testing.T) {
	tmpDir := t.TempDir()
	err := Restore(tmpDir, RestoreOptions{})
	if err == nil {
		t.Fatal("expected an error when no backups exist")
	}
}

func TestRestoreUsesNewestBackup(t *testing.T) {
	tmpDir := t.TempDir()
	target := filepath.Join(tmpDir, "notes.go")

	// Two successive runs, each backing up a different version of the file.
	for _, content := range []string{"package a // by Claude\n", "package b // by Claude\n"} {
		if err := os.WriteFile(target, []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
		c := New(tmpDir, Options{Backup: true})
		if err := c.CleanSourceComments(); err != nil {
			t.Fatal(err)
		}
		if _, err := c.FinalizeBackup(); err != nil {
			t.Fatal(err)
		}
	}

	if err := Restore(tmpDir, RestoreOptions{}); err != nil {
		t.Fatalf("Restore() error = %v", err)
	}
	got, _ := os.ReadFile(target)
	if want := "package b // by Claude\n"; string(got) != want {
		t.Errorf("restored the wrong backup:\ngot:  %q\nwant: %q", string(got), want)
	}
}

func TestBackupDirIsNotWalked(t *testing.T) {
	tmpDir := t.TempDir()
	setupTestFiles(t, tmpDir, map[string]string{
		"CLAUDE.md": "instructions",
		"main.go":   "package main // by Claude\n",
	})

	c := New(tmpDir, Options{Backup: true})
	if err := c.CleanAIArtifacts(); err != nil {
		t.Fatal(err)
	}
	if err := c.CleanSourceComments(); err != nil {
		t.Fatal(err)
	}
	if _, err := c.FinalizeBackup(); err != nil {
		t.Fatal(err)
	}

	// A second run must not touch the backed-up copies.
	c2 := New(tmpDir, Options{Backup: false})
	for _, step := range c2.Steps() {
		if step.Key == "history" {
			continue
		}
		if err := step.Run(); err != nil {
			t.Fatalf("step %s failed: %v", step.Key, err)
		}
	}

	dir, err := latestBackup(tmpDir)
	if err != nil || dir == "" {
		t.Fatalf("backup dir missing after second run: %v", err)
	}
	got, err := os.ReadFile(filepath.Join(dir, "CLAUDE.md"))
	if err != nil {
		t.Fatalf("backed-up CLAUDE.md was removed by a later run: %v", err)
	}
	if string(got) != "instructions" {
		t.Errorf("backed-up content altered: %q", string(got))
	}
}

func TestHasWorkingTreeChanges(t *testing.T) {
	tests := []struct {
		name   string
		status string
		want   bool
	}{
		{"clean", "", false},
		{"modified file", " M main.go\n", true},
		{"untracked file", "?? notes.txt\n", true},
		{"only backup dir", "?? " + backupDirName + "/\n", false},
		{"backup dir entry", "?? " + backupDirName + "/20260101-000000/main.go\n", false},
		{"backup plus real change", "?? " + backupDirName + "/\n M main.go\n", true},
		{"quoted path", "?? \"" + backupDirName + "/\"\n", false},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := hasWorkingTreeChanges(tt.status); got != tt.want {
				t.Errorf("hasWorkingTreeChanges(%q) = %v, want %v", tt.status, got, tt.want)
			}
		})
	}
}
