package cleaner

import (
	"strings"
	"testing"
)

// Watermark-scrubbing benchmarks live in pkg/watermark, alongside the code.

func BenchmarkCleanCommentsInSource(b *testing.B) {
	pattern := CompiledCommentAIPattern()
	var sb strings.Builder
	for i := 0; i < 100; i++ {
		sb.WriteString("func f() { doWork() } // ordinary trailing comment\n")
		sb.WriteString("// Generated by Claude for this helper\n")
		sb.WriteString("var x = 1\n")
	}
	src := []byte(sb.String())
	b.SetBytes(int64(len(src)))
	b.ReportAllocs()
	for b.Loop() {
		CleanCommentsInSource(src, ".go", pattern)
	}
}

func BenchmarkCleanCommitMessage(b *testing.B) {
	patterns := CompiledCommitMessagePatterns()
	msg := "Add feature\n\n" +
		"Implements the thing with care.\n" +
		"Co-Authored-By: Claude <noreply@anthropic.com>\n" +
		"https://claude.ai/code/session_01H\n"
	b.ReportAllocs()
	for b.Loop() {
		cleanCommitMessage(msg, patterns)
	}
}
